import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { RouterModule } from '@angular/router';
import { HttpClientModule } from '@angular/common/http';
import { provideRouter } from '@angular/router';

import { AppComponent } from './app.component';
import { PropertyFormComponent } from './components/property-form/property-form.component'; // Importar componentes
import { EditPropertyComponent } from './components/edit-property/edit-property.component'; // Importar componentes
import { UserDetailsComponent } from './components/user-details/user-details.component'; // Importar componentes
import { routes } from './app.routes';  // Asegúrate de que la ruta sea correcta.

@NgModule({
  declarations: [
    AppComponent, // Tu componente raíz.
    PropertyFormComponent, // Componente de formulario de propiedad
    EditPropertyComponent, // Componente para editar propiedad
    UserDetailsComponent, // Componente de detalles de usuario
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    RouterModule.forRoot(routes), // Aquí importas el RouterModule con tus rutas definidas.
  ],
  providers: [],
  bootstrap: [AppComponent], // El componente que se cargará al inicio de la aplicación.
})
export class AppModule {}
